import { truncateAllTables } from "../../../test/truncateTables";
import addCustomer from "./addCustomer.test";
import addProductToReservation from "./addProductToReservation.test";
import createEmployee from "./createEmployee.test";
import createProduct from "./createProduct.test";
import createReservation from "./createReservation.test";
import createSchedule from "./createSchedule.test";
import createVacation from "./createVacation.test";
import deleteAllEmployees from "./deleteAllEmployees.test";
import deleteAllProducts from "./deleteAllProducts.test";
import deleteAllReservations from "./deleteAllReservations.test";
import deleteAllSchedules from "./deleteAllSchedules.test";
import deleteAllVacations from "./deleteAllVacations.test";
import deleteOneEmployee from "./deleteOneEmployee.test";
import deleteOneProduct from "./deleteOneProduct.test";
import deleteOneReservation from "./deleteOneReservation.test";
import deleteOneSchedule from "./deleteOneSchedule.test";
import deleteOneVacation from "./deleteOneVacation.test";
import findAll from "./findAll.test";
import findAllEmployees from "./findAllEmployees.test";
import findAllReservations from "./findAllReservations.test";
import findAllSchedules from "./findAllSchedules.test";
import findAllVacations from "./findAllVacations.test";
import updateEmployee from "./updateEmployee.test";
import updateProduct from "./updateProduct.test";
import updateReservation from "./updateReservation.test";
import updateSchedule from "./updateSchedule.test";
import updateVacation from "./updateVacation.test";

beforeEach(async (done) => {
  await truncateAllTables();
  done();
});

describe("Business controller", () => {
  // it("should add a customer", addCustomer);
  // it("should add a product to a reservation", addProductToReservation);
  it("should create an employee", createEmployee);
  it("should create a product", createProduct);
  it("should create a reservation", createReservation);
  it("should create a schedule", createSchedule);
  it("should create a vacation", createVacation);
  it("should delete all employees", deleteAllEmployees);
  it("should delete all products", deleteAllProducts);
  it("should delete all reservations", deleteAllReservations);
  it("should delete all schedules", deleteAllSchedules);
  it("should delete all vacations", deleteAllVacations);
  it("should delete an employee", deleteOneEmployee);
  it("should delete a product", deleteOneProduct);
  it("should delete a reservation", deleteOneReservation);
  // it("should delete a schedule", deleteOneSchedule);
  // it("should delete a vacation", deleteOneVacation);
  it("should retrieve all business", findAll);
  it("should retrieve all employees", findAllEmployees);
  it("should retrieve all reservations", findAllReservations);
  it("should retrieve all schedules", findAllSchedules);
  it("should retrieve all vacations", findAllVacations);
  it("should update an employee", updateEmployee);
  it("should update a product", updateProduct);
  it("should update a reservation", updateReservation);
  it("should update a schedule", updateSchedule);
  it("should update a vacation", updateVacation);
});
