import { truncateAllTables } from "../../../test/truncateTables";
import addCustomer from "./addCustomer";
import addProductToReservation from "./addProductToReservation";
import createEmployee from "./createEmployee";
import createProduct from "./createProduct";
import createReservation from "./createReservation";
import createSchedule from "./createSchedule";
import createVacation from "./createVacation";
import deleteAllEmployees from "./deleteAllEmployees";
import deleteAllProducts from "./deleteAllProducts";
import deleteAllReservations from "./deleteAllReservations";
import deleteAllSchedules from "./deleteAllSchedules";
import deleteAllVacations from "./deleteAllVacations";
import deleteOneEmployee from "./deleteOneEmployee";
import deleteOneProduct from "./deleteOneProduct";
import deleteOneReservation from "./deleteOneReservation";
import deleteOneSchedule from "./deleteOneSchedule";
import deleteOneVacation from "./deleteOneVacation";
import findAll from "./findAll";
import findAllEmployees from "./findAllEmployees";
import findAllReservations from "./findAllReservations";
import findAllSchedules from "./findAllSchedules";
import findAllVacations from "./findAllVacations";
import updateEmployee from "./updateEmployee";
import updateProduct from "./updateProduct";
import updateReservation from "./updateReservation";
import updateSchedule from "./updateSchedule";
import updateVacation from "./updateVacation";

beforeEach(async (done) => {
  await truncateAllTables();
  done();
});

describe("Business controller", () => {
  // it("should add a customer", addCustomer);
  // it("should add a product to a reservation", addProductToReservation);
  it("should create an employee", createEmployee);
  it("should create a product", createProduct);
  it("should create a reservation", createReservation);
  it("should create a schedule", createSchedule);
  it("should create a vacation", createVacation);
  it("should delete all employees", deleteAllEmployees);
  it("should delete all products", deleteAllProducts);
  it("should delete all reservations", deleteAllReservations);
  it("should delete all schedules", deleteAllSchedules);
  it("should delete all vacations", deleteAllVacations);
  it("should delete an employee", deleteOneEmployee);
  it("should delete a product", deleteOneProduct);
  it("should delete a reservation", deleteOneReservation);
  // it("should delete a schedule", deleteOneSchedule);
  // it("should delete a vacation", deleteOneVacation);
  it("should retrieve all business", findAll);
  it("should retrieve all employees", findAllEmployees);
  it("should retrieve all reservations", findAllReservations);
  it("should retrieve all schedules", findAllSchedules);
  it("should retrieve all vacations", findAllVacations);
  it("should update an employee", updateEmployee);
  it("should update a product", updateProduct);
  it("should update a reservation", updateReservation);
  it("should update a schedule", updateSchedule);
  it("should update a vacation", updateVacation);
});
