import { truncateAllTables } from "../../../test/truncateTables";
import addCustomer from "./addCustomer.spec";
import addProductToReservation from "./addProductToReservation.spec";
import addSchedule from "./addSchedule.spec";
import createEmployee from "./createEmployee.spec";
import createProduct from "./createProduct.spec";
import createReservation from "./createReservation.spec";
import createSchedule from "./createSchedule.spec";
import createVacation from "./createVacation.spec";
import deleteAllEmployees from "./deleteAllEmployees.spec";
import deleteAllProducts from "./deleteAllProducts.spec";
import deleteAllReservations from "./deleteAllReservations.spec";
import deleteAllSchedules from "./deleteAllSchedules.spec";
import deleteAllVacations from "./deleteAllVacations.spec";
import deleteOneEmployee from "./deleteOneEmployee.spec";
import deleteOneProduct from "./deleteOneProduct.spec";
import deleteOneReservation from "./deleteOneReservation.spec";
import deleteOneSchedule from "./deleteOneSchedule.spec";
import deleteOneVacation from "./deleteOneVacation.spec";
import findAll from "./findAll.spec";
import findAllEmployees from "./findAllEmployees.spec";
import findAllReservations from "./findAllReservations.spec";
import findAllSchedules from "./findAllSchedules.spec";
import findAllVacations from "./findAllVacations.spec";
import findOneSchedule from "./findOneSchedule.spec";
import updateEmployee from "./updateEmployee.spec";
import updateProduct from "./updateProduct.spec";
import updateReservation from "./updateReservation.spec";
import updateSchedule from "./updateSchedule.spec";
import updateVacation from "./updateVacation.spec";

beforeEach(async (done) => {
  await truncateAllTables();
  done();
});

describe("Business controller", () => {
  // it("should add a customer", addCustomer);
  // it("should add a product to a reservation", addProductToReservation);
  it("should create an employee", createEmployee);
  it("should create a product", createProduct);
  it("should add a schedule", addSchedule);
  it("should create a reservation", createReservation);
  it("should create a schedule", createSchedule);
  it("should create a vacation", createVacation);
  it("should delete all employees", deleteAllEmployees);
  it("should delete all products", deleteAllProducts);
  it("should delete all reservations", deleteAllReservations);
  it("should delete all schedules", deleteAllSchedules);
  it("should delete all vacations", deleteAllVacations);
  it("should delete an employee", deleteOneEmployee);
  it("should delete a product", deleteOneProduct);
  it("should delete a reservation", deleteOneReservation);
  // it("should delete a schedule", deleteOneSchedule);
  // it("should delete a vacation", deleteOneVacation);
  it("should retrieve all business", findAll);
  it("should retrieve all employees", findAllEmployees);
  it("should retrieve all reservations", findAllReservations);
  it("should retrieve all schedules", findAllSchedules);
  it("should retrieve all vacations", findAllVacations);
  it("should retrieve one schedule", findOneSchedule);
  it("should update an employee", updateEmployee);
  it("should update a product", updateProduct);
  it("should update a reservation", updateReservation);
  it("should update a schedule", updateSchedule);
  it("should update a vacation", updateVacation);
});
